2020-07-30 21:52:03.118050: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-30 21:52:03.132526: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-30 21:52:03.132849: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-07-30 21:52:03.132974: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-30 21:52:03.134074: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-30 21:52:03.135109: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-30 21:52:03.135273: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-30 21:52:03.136383: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-30 21:52:03.137065: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-30 21:52:03.153161: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-30 21:52:03.153265: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-30 21:52:03.153861: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-30 21:52:03.154252: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-07-30 21:52:03.154425: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-07-30 21:52:03.158328: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 4200000000 Hz
2020-07-30 21:52:03.158582: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f5b29233c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-30 21:52:03.158595: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-30 21:52:03.158732: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-30 21:52:03.159278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-07-30 21:52:03.159313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-30 21:52:03.159325: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-30 21:52:03.159336: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-30 21:52:03.159347: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-30 21:52:03.159357: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-30 21:52:03.159367: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-30 21:52:03.159378: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-30 21:52:03.159422: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-30 21:52:03.160014: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-30 21:52:03.160403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-07-30 21:52:03.160424: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-30 21:52:03.329378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-30 21:52:03.329396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-07-30 21:52:03.329401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-07-30 21:52:03.330243: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-30 21:52:03.330578: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-30 21:52:03.330880: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-30 21:52:03.331173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10341 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-07-30 21:52:03.332354: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f5b3e13460 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-30 21:52:03.332365: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
2020-07-30 21:52:06.315932: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-30 21:52:06.759860: W tensorflow/stream_executor/gpu/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once.
2020-07-30 21:52:06.778804: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-30 21:52:07.826122: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-07-30 21:52:07.826148: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1259] Profiler found 1 GPUs
2020-07-30 21:52:07.826610: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.1
2020-07-30 21:52:07.927103: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-07-30 21:52:07.928674: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-07-30 21:52:08.066250: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2020-07-30 21:52:08.066286: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.



MODEL:cnn_dice_EXTDATApp_augmentation_small
Train for 1928 steps, validate for 13 steps
Epoch 1/100

Epoch 00001: val_loss improved from inf to 0.25414, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 261s - loss: 0.3320 - accuracy: 0.8769 - f1: 0.6980 - mean_io_u: 0.6729 - val_loss: 0.2541 - val_accuracy: 0.9112 - val_f1: 0.7834 - val_mean_io_u: 0.7702
Epoch 2/100

Epoch 00002: val_loss improved from 0.25414 to 0.23463, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.2586 - accuracy: 0.9109 - f1: 0.7572 - mean_io_u: 0.7470 - val_loss: 0.2346 - val_accuracy: 0.9172 - val_f1: 0.7679 - val_mean_io_u: 0.7635
Epoch 3/100

Epoch 00003: val_loss improved from 0.23463 to 0.20292, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.2391 - accuracy: 0.9193 - f1: 0.7771 - mean_io_u: 0.6603 - val_loss: 0.2029 - val_accuracy: 0.9307 - val_f1: 0.8187 - val_mean_io_u: 0.4542
Epoch 4/100

Epoch 00004: val_loss did not improve from 0.20292
1928/1928 - 257s - loss: 0.2175 - accuracy: 0.9267 - f1: 0.7918 - mean_io_u: 0.5317 - val_loss: 0.2032 - val_accuracy: 0.9326 - val_f1: 0.8307 - val_mean_io_u: 0.4407
Epoch 5/100

Epoch 00005: val_loss improved from 0.20292 to 0.17275, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.2040 - accuracy: 0.9313 - f1: 0.8017 - mean_io_u: 0.5435 - val_loss: 0.1728 - val_accuracy: 0.9411 - val_f1: 0.8507 - val_mean_io_u: 0.4326
Epoch 6/100

Epoch 00006: val_loss did not improve from 0.17275
1928/1928 - 257s - loss: 0.1988 - accuracy: 0.9329 - f1: 0.8056 - mean_io_u: 0.5393 - val_loss: 0.1795 - val_accuracy: 0.9408 - val_f1: 0.8493 - val_mean_io_u: 0.4313
Epoch 7/100

Epoch 00007: val_loss did not improve from 0.17275
1928/1928 - 257s - loss: 0.1919 - accuracy: 0.9353 - f1: 0.8110 - mean_io_u: 0.5640 - val_loss: 0.2066 - val_accuracy: 0.9357 - val_f1: 0.8306 - val_mean_io_u: 0.4384
Epoch 8/100

Epoch 00008: val_loss did not improve from 0.17275
1928/1928 - 257s - loss: 0.1826 - accuracy: 0.9383 - f1: 0.8192 - mean_io_u: 0.7059 - val_loss: 0.2864 - val_accuracy: 0.9028 - val_f1: 0.7235 - val_mean_io_u: 0.7341
Epoch 9/100

Epoch 00009: val_loss improved from 0.17275 to 0.16035, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.1812 - accuracy: 0.9390 - f1: 0.8215 - mean_io_u: 0.7314 - val_loss: 0.1603 - val_accuracy: 0.9480 - val_f1: 0.8720 - val_mean_io_u: 0.8560
Epoch 10/100

Epoch 00010: val_loss improved from 0.16035 to 0.15328, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.1742 - accuracy: 0.9414 - f1: 0.8273 - mean_io_u: 0.7847 - val_loss: 0.1533 - val_accuracy: 0.9503 - val_f1: 0.8781 - val_mean_io_u: 0.8619
Epoch 11/100

Epoch 00011: val_loss did not improve from 0.15328
1928/1928 - 257s - loss: 0.1725 - accuracy: 0.9418 - f1: 0.8287 - mean_io_u: 0.7911 - val_loss: 0.1558 - val_accuracy: 0.9476 - val_f1: 0.8693 - val_mean_io_u: 0.8539
Epoch 12/100

Epoch 00012: val_loss did not improve from 0.15328
1928/1928 - 257s - loss: 0.1682 - accuracy: 0.9432 - f1: 0.8327 - mean_io_u: 0.8140 - val_loss: 0.1588 - val_accuracy: 0.9496 - val_f1: 0.8735 - val_mean_io_u: 0.8582
Epoch 13/100

Epoch 00013: val_loss improved from 0.15328 to 0.14475, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.1668 - accuracy: 0.9440 - f1: 0.8349 - mean_io_u: 0.8147 - val_loss: 0.1448 - val_accuracy: 0.9517 - val_f1: 0.8792 - val_mean_io_u: 0.8629
Epoch 14/100

Epoch 00014: val_loss did not improve from 0.14475
1928/1928 - 257s - loss: 0.1663 - accuracy: 0.9440 - f1: 0.8331 - mean_io_u: 0.8161 - val_loss: 0.1860 - val_accuracy: 0.9410 - val_f1: 0.8494 - val_mean_io_u: 0.8366
Epoch 15/100

Epoch 00015: val_loss improved from 0.14475 to 0.13870, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.1594 - accuracy: 0.9460 - f1: 0.8398 - mean_io_u: 0.8285 - val_loss: 0.1387 - val_accuracy: 0.9518 - val_f1: 0.8802 - val_mean_io_u: 0.8648
Epoch 16/100

Epoch 00016: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1568 - accuracy: 0.9469 - f1: 0.8428 - mean_io_u: 0.8321 - val_loss: 0.1501 - val_accuracy: 0.9514 - val_f1: 0.8777 - val_mean_io_u: 0.8616
Epoch 17/100

Epoch 00017: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1583 - accuracy: 0.9469 - f1: 0.8419 - mean_io_u: 0.8344 - val_loss: 0.1463 - val_accuracy: 0.9500 - val_f1: 0.8810 - val_mean_io_u: 0.8645
Epoch 18/100

Epoch 00018: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1546 - accuracy: 0.9475 - f1: 0.8441 - mean_io_u: 0.8373 - val_loss: 0.1493 - val_accuracy: 0.9514 - val_f1: 0.8834 - val_mean_io_u: 0.8670
Epoch 19/100

Epoch 00019: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1541 - accuracy: 0.9477 - f1: 0.8441 - mean_io_u: 0.8377 - val_loss: 0.1822 - val_accuracy: 0.9394 - val_f1: 0.8427 - val_mean_io_u: 0.8280
Epoch 20/100

Epoch 00020: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1507 - accuracy: 0.9487 - f1: 0.8467 - mean_io_u: 0.8416 - val_loss: 0.1466 - val_accuracy: 0.9517 - val_f1: 0.8825 - val_mean_io_u: 0.8657
Epoch 21/100

Epoch 00021: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1492 - accuracy: 0.9489 - f1: 0.8483 - mean_io_u: 0.8425 - val_loss: 0.1421 - val_accuracy: 0.9541 - val_f1: 0.8858 - val_mean_io_u: 0.8704
Epoch 22/100

Epoch 00022: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1468 - accuracy: 0.9498 - f1: 0.8513 - mean_io_u: 0.8423 - val_loss: 0.1511 - val_accuracy: 0.9510 - val_f1: 0.8750 - val_mean_io_u: 0.8584
Epoch 23/100

Epoch 00023: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1478 - accuracy: 0.9495 - f1: 0.8487 - mean_io_u: 0.8448 - val_loss: 0.1452 - val_accuracy: 0.9522 - val_f1: 0.8821 - val_mean_io_u: 0.8660
Epoch 24/100

Epoch 00024: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1458 - accuracy: 0.9502 - f1: 0.8514 - mean_io_u: 0.8455 - val_loss: 0.1445 - val_accuracy: 0.9522 - val_f1: 0.8808 - val_mean_io_u: 0.8645
Epoch 25/100

Epoch 00025: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1425 - accuracy: 0.9510 - f1: 0.8527 - mean_io_u: 0.8482 - val_loss: 0.1774 - val_accuracy: 0.9447 - val_f1: 0.8564 - val_mean_io_u: 0.8419
Epoch 26/100

Epoch 00026: val_loss did not improve from 0.13870
1928/1928 - 257s - loss: 0.1428 - accuracy: 0.9509 - f1: 0.8532 - mean_io_u: 0.8487 - val_loss: 0.1489 - val_accuracy: 0.9498 - val_f1: 0.8743 - val_mean_io_u: 0.8580
Epoch 27/100

Epoch 00027: val_loss improved from 0.13870 to 0.12906, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.1413 - accuracy: 0.9516 - f1: 0.8543 - mean_io_u: 0.8502 - val_loss: 0.1291 - val_accuracy: 0.9563 - val_f1: 0.8924 - val_mean_io_u: 0.8768
